apiVersion: apps/v1
kind: Deployment
metadata:
  name: appspring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appspring
  template:
    metadata:
      labels:
        app: appspring
    spec:
      containers:
      - name: appspring
        image: khatanve/appspring:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: appspring-service
spec:
  selector:
    app: appspring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort