deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VM_SSH_PRIVATE_KEY }}

    - name: Deploy to Minikube on VM
      run: |
        ssh ${{ secrets.VM_SSH_USER }}@${{ secrets.VM_SSH_HOST }} << 'EOF'
          cd ~/my-app/
          minikube start  # Start Minikube if not already running
          
          # Apply the manifest file
          kubectl apply -f appspring-manifest.yaml
          
          # Verify deployment
          kubectl get pods
          kubectl get svc
        EOF