name: SSH Command Execution

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.10.134
        username: tanveer
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: whoami
        timeout: 60s


