name: remote ssh command
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest        

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VM_SSH_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: date

